# Generated by Django 4.2.4 on 2023-10-25 15:46

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_carousel_languageexperience_qualificationexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workexperience',
            name='longDescription3',
        ),
        migrations.AlterField(
            model_name='carousel',
            name='image',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='videoLink',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='languageexperience',
            name='image',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='qualificationexperience',
            name='image',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='qualificationexperience',
            name='qualificationLink',
            field=models.FileField(upload_to=blog.models.filePathFile),
        ),
        migrations.AlterField(
            model_name='softwareexperience',
            name='image',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='image1',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='image2',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='image3',
            field=models.ImageField(upload_to=blog.models.filePathImage),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='longDescription1',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='longDescription2',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='shortDescription',
            field=models.TextField(),
        ),
    ]
