# Generated by Django 4.2.4 on 2023-10-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_workexperience_longdescription3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='link',
            field=models.CharField(max_length=150),
        ),
    ]
